/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_8405be07 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/usorqldwroecyxucmtuw/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_8405be07").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }

  // Intercept and synchronize matching email/OneDrive account credentials across profiles
  if (key.startsWith("email_account:") && !key.includes(":by_email:") && value && value.provider && value.email) {
    try {
      const { data } = await supabase
        .from("kv_store_8405be07")
        .select("key, value")
        .like("key", "email_account:%");
      
      if (data && data.length > 0) {
        const targetEmail = String(value.email).toLowerCase().trim();
        const targetProvider = value.provider;
        const updates: any[] = [];
        
        for (const row of data) {
          if (row.key === key || row.key.includes(":by_email:")) continue;
          const val = row.value || {};
          if (
            val.provider === targetProvider && 
            String(val.email).toLowerCase().trim() === targetEmail
          ) {
            // Check if the current tokens are actually different, to avoid infinite recursion
            if (
              val.access_token !== value.access_token ||
              val.refresh_token !== value.refresh_token ||
              val.token_expires_at !== value.token_expires_at
            ) {
              const updatedVal = {
                ...val,
                access_token: value.access_token,
                refresh_token: value.refresh_token || val.refresh_token,
                token_expires_at: value.token_expires_at,
                status: value.status || val.status || 'active',
                connected: true
              };
              updates.push({
                key: row.key,
                value: updatedVal
              });
            }
          }
        }
        
        if (updates.length > 0) {
          console.log(`[Credential Sync] Syncing tokens for ${targetEmail} across ${updates.length} other profiles.`);
          // Do upsert on other rows directly
          await supabase.from("kv_store_8405be07").upsert(updates);
        }
      }
    } catch (e: any) {
      console.error("[Credential Sync Error] Failed to sync email credentials:", e?.message || e);
    }
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_8405be07").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_8405be07").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_8405be07").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_8405be07").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_8405be07").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_8405be07").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};